#!/bin/bash

# G.A. Library Developer support tools 

# Copyright Ronaldo Faria Lima (C) 2004 - All rights reserved 

# Feel free to contact the author in <ronaldo@ronaldolima.eti.br>

# This file is part of G.A. Lib.

# G.A. Lib is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

# G.A. Lib is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with G.A. Lib; if not, write to the Free Software Foundation,
# Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA

#  System: G.A. Lib

#  Description: Indentation script for source code beautification

# $Id: gaindent,v 1.1 2004-10-20 10:31:32 ron_lima Exp $


# Command line checking
if [ $# -eq 0 ]
then
    echo "Usage: $0 <filename>"
fi

if [ ! -w $1 ]
then
    echo "Could not open file $1 for reading/writting..."
else
    # Makes the indentation
    indent -nbad -bap -nbc -bbb -ncdb -bl -nce -di2 -ndj -nfc1 -i2 -ip \
           -lp -psl -pcs -nsc -nsob $1
    # Deletes all tabs from the file
    cat $1 | sed 's/^[	]/    /' > $1.tmp
    mv $1.tmp $1
fi
