\input texinfo @c -*-texinfo-*-
@c $Id: queue.texi,v 1.3 2005-02-19 22:13:47 ron_lima Exp $
@c %**start of header
@setfilename queue.info
@settitle    Queue routines
@c %**end of header

@copying
@c ** Copyrght
Copyright @copyright{} 2004 - Ronaldo Faria Lima - All rights reserved
@end copying

@titlepage
@c ** Title page

@title G.A. Library
@subtitle Queue interfaces
@author Ronaldo Faria Lima

@c ** Copyright page
@page
@insertcopying
@end titlepage

@c ** Table of contents
@contents

@c ** The top node
@ifnottex
@node Top, algorithm, (dir), (dir)
@top Queue
@end ifnottex

@c ** Main Menu
@menu
* algorithm :: Algorithm implemented by G.A. Library
* data types:: Data types
* functions :: Description of all available functions
* Licenses  :: Licenses and other information
@end menu

@c ***** algorithm
@node algorithm, data types, Top, Top
@chapter Queue implementation in G.A. Library

The queue algorithm is a data structure where the first item to get in
will be the first item to get out. G.A. Library uses the single lists
algorithm as the queue implementation basis.

Like stacks, queue functions are front-ends for lists operations.

To add queue algorithms to your program, simply include the queue.h
header file. All needed declarations for lists are there.

@c ***** data types
@node data types, functions, algorithm, Top
@chapter Data types

In order to implement the queues, the following data types are
defined:

@itemize @bullet
@item queue_t
Queue descriptor. Describes the entire queue.
@end itemize

@c ***** functions
@node functions, Licenses , data types, Top
@chapter Functions

@c ***** functions menu
@menu
* queue_init    :: Initializes a queue descriptor
* queue_destroy :: Destroys the queue descriptor
* queue_pop     :: Gets (pops) an item from the queue
* queue_push    :: Adds (pushes) an item into the queue
@end menu

@c ***** queue_init
@node queue_init, queue_destroy, functions, functions
@section int queue_init (queue_t *queue, deallocator_t *dealloc)

Purpose: Initializes a queue descriptor and makes it available for
usage.

Parameters:
@itemize @bullet
@item queue
Queue descriptor to initialize
@item dealloc
Deallocator to use to clean up memory when each element of the queue
is popped.
@end itemize

@emph{Hints}:
@itemize @bullet
@item
The deallocator is used effectively only by the queue_free
routine. Even though, you have to provide it in order to avoid memory
leaks when deleting the queue from memory.
@end itemize

@inforef{list_init, List initialization routine, list.info}, for more
information.

@c ***** queue_destroy
@node queue_destroy, queue_pop, queue_init, functions
@section int queue_destroy (queue_t *queue)

Purpose: Deletes the entire queue from the memory

Parameters:
@itemize @bullet
@item queue
Queue descriptor to destroy
@end itemize

@inforef{list_destroy, List destruction routine, list.info}, for more
information.

@c ***** queue_pop
@node queue_pop, queue_push, queue_destroy, functions
@section int queue_pop (queue_t *queue, void **data)

Purpose: Gets (pops) an element from the queue

Parameters:
@itemize @bullet
@item queue
Queue descriptor
@item data
Data popped from the queue
@end itemize

@inforef{list_del, List deletion routine, list.info}, for more
information.

@c ***** queue_push
@node queue_push,  , queue_pop, functions
@section int queue_push (queue_t *queue, const void *data)

Purpose: Adds (pushes) a new element to the queue

Parameters:
@itemize @bullet
@item queue
Queue descriptor
@item data
Data to push into the queue
@end itemize

@inforef{list_insert, List insertion routine, list.info}, for more
information.

@c ** Includes the licenses 
@node Licenses, ,functions, Top
@include licenses.texi

@bye
